package runtimelab

import "time"

const (
	openClawRepo = "https://github.com/openclaw/openclaw"
	hermesRepo   = "https://github.com/NousResearch/hermes-agent"
	odysseusRepo = "https://github.com/odysseus-dev/odysseus"
)

func reviewedRuntimeInventories() []RuntimeParityInventory {
	reviewedAt := time.Date(2026, 8, 8, 0, 0, 0, 0, time.UTC)
	return []RuntimeParityInventory{
		{
			RuntimeID: "openclaw", Project: "OpenClaw", RepositoryURL: openClawRepo,
			DefaultBranch: "main", ReviewedRevision: "fa9626c4e1002d83e6c06a09ad670c8f41f8b24e",
			ReviewedRelease: "v2026.7.1-2", ReviewedAt: reviewedAt, License: "MIT",
			LicensePolicy:    "Remote protocol integration and selective MIT adaptation are permitted, subject to attribution and HAI security review.",
			ReadinessCeiling: "declared", CanonicalAuthority: "HAI PostgreSQL Operation Ledger and HAI policy remain authoritative.",
			Features: openClawFeatures(),
		},
		{
			RuntimeID: "hermes", Project: "Hermes Agent", RepositoryURL: hermesRepo,
			DefaultBranch: "main", ReviewedRevision: "b3aa561faffd64f05436e429a6415d175e534ec9",
			ReviewedRelease: "v2026.8.3", ReviewedAt: reviewedAt, License: "MIT",
			LicensePolicy:    "Remote protocol integration and selective MIT adaptation are permitted, subject to attribution and HAI security review.",
			ReadinessCeiling: "declared", CanonicalAuthority: "HAI PostgreSQL Operation Ledger and HAI policy remain authoritative.",
			Features: hermesFeatures(),
		},
		{
			RuntimeID: "odysseus", Project: "Odysseus", RepositoryURL: odysseusRepo,
			DefaultBranch: "dev", ReviewedRevision: "e4fa4ae5dd1d709ce4168397bd1d200fec1b2494",
			ReviewedAt: reviewedAt, License: "AGPL-3.0-or-later",
			LicensePolicy:    "Do not copy or link Odysseus implementation into HAI. Use documented behavior as a design reference or interoperate with a separately deployed service after legal and security review.",
			ReadinessCeiling: "declared", CanonicalAuthority: "HAI PostgreSQL Operation Ledger and HAI policy remain authoritative.",
			Features: odysseusFeatures(),
		},
	}
}

func openClawFeatures() []RuntimeFeature {
	readme := openClawRepo + "/blob/main/README.md"
	protocol := openClawRepo + "/blob/main/docs/gateway/protocol.md"
	multiAgent := openClawRepo + "/blob/main/docs/concepts/multi-agent.md"
	skills := openClawRepo + "/blob/main/docs/tools/skills.md"
	security := openClawRepo + "/blob/main/SECURITY.md"
	return []RuntimeFeature{
		deferred(feature("openclaw-gateway", "Gateway and isolated agent definitions", "Expose one local control plane for agent sessions, tools, events, and channel bindings.", "A WebSocket JSON protocol connects scoped clients to isolated agent workspaces and session stores.", []string{"agent_runtimes", "agent_definitions", "goal_handling"}, []string{"Node.js", "OpenClaw Gateway", "gateway token or approved local pairing"}, "MIT", "A reachable gateway is powerful and client capability declarations are not authorization.", "Runtime Lab adapter and HAI agent-team contracts", "Use a typed, scope-minimized Gateway client beneath HAI authorization; retain HAI as canonical state and admit only bounded delegated sessions.", DispositionAdaptedForHAI, "partial", "read_only_discovery_and_bounded_delegated_session_contract_tested", "source_reviewed", []string{readme, protocol, multiAgent}), "P0", "Keep discovery and artifact metadata import read-only. Require a separately configured delegation token and explicit HAI authority for any bounded session admission.", "Pinned OpenClaw release", "loopback or explicitly allowlisted endpoint", "protocol fixtures", "operator credentials"),
		deferred(feature("openclaw-planning", "Embedded agent loop and planning", "Turn a request into model and tool activity.", "OpenClaw owns prompt assembly, model discovery, tools, and an embedded agent turn.", []string{"planning", "replanning", "reasoning_patterns"}, []string{"model provider", "OpenClaw agent runtime"}, "MIT", "Allowing an external loop to own goals or completion would create a competing source of truth.", "HAI Plan Graph, task engine, workflow engine, and verification", "Reuse the OpenClaw agent loop beneath HAI goals, budgets, approvals, and final verification.", DispositionAdaptedForHAI, "partial", "hai_contract_tested", "documented", []string{readme, openClawRepo + "/blob/main/docs/agent.md"}), "P0", "Wire structured plan/checkpoint and result handoffs into the existing delegated-session path; HAI-native planning alone does not prove integration.", "owner-bound plan and run mapping", "checkpoint and result schema", "real delegated planning acceptance"),
		deferred(feature("openclaw-capabilities", "Tools, MCP, skills, plugins, and extensions", "Extend the agent with discoverable capabilities and reusable instructions.", "Tools, layered skills, plugins, and node-hosted skills are filtered by effective policy and allowlists.", []string{"tool_use", "mcp", "skills", "plugins", "extensions"}, []string{"OpenClaw plugin SDK", "skill directories", "optional MCP servers"}, "MIT", "Community plugins and skills are executable supply-chain inputs and may inject instructions or secrets.", "HAI capability contracts, Brain Catalog, MCP preflight, and tool allowlists", "Project only reviewed metadata into HAI; require digest, provenance, explicit allowlisting, and preflight before a capability can become available.", DispositionAdaptedForHAI, "partial", "gateway_capability_and_prepared_model_aggregate_tested", "documented", []string{skills, protocol, openClawRepo + "/blob/main/docs/plugins.md"}), "P0", "Keep aggregate discovery read-only; add signed capability-card import and per-capability supply-chain review before any capability becomes available.", "Pinned plugin SDK schema", "supply-chain review", "capability digest and provenance"),
		deferred(feature("openclaw-memory", "Session, transcript, memory, and bounded recall", "Retain per-agent context while supporting redacted cross-session recall.", "Per-agent SQLite session stores and workspace memory provide isolated history; bounded recall strips sensitive tool detail.", []string{"memory", "context_management", "knowledge_retrieval"}, []string{"per-agent state directories", "SQLite"}, "MIT", "OAuth or session-store sharing can leak identity and raw transcripts; workspaces are not hard sandboxes.", "HAI memory engine, source evidence, project memory, and owner isolation", "Reuse upstream session/context and recall APIs with owner-scoped HAI context injection and provenance-linked result import; keep verified HAI memory canonical without sharing raw session databases.", DispositionAdaptedForHAI, "partial", "hai_memory_tested", "documented", []string{multiAgent, openClawRepo + "/blob/main/docs/concepts/memory.md"}), "P0", "Implement bounded context export and returned evidence import with owner isolation, retention, correction, and source provenance.", "owner-scoped context contract", "source-linked import and retention", "cross-owner isolation acceptance"),
		deferred(feature("openclaw-multi-agent", "Multi-agent routing and delegation", "Route channel accounts and sessions to isolated specialist agents.", "Bindings map channel accounts to per-agent workspaces, auth profiles, and sessions.", []string{"multi_agent_orchestration", "delegation", "parallel_execution"}, []string{"Gateway", "agent bindings", "separate state directories"}, "MIT", "Bindings are routing, not HAI approval; absolute paths remain host-reachable unless sandboxed.", "HAI agent teams, typed messages, acknowledgments, and Plan Graph", "Translate HAI delegation envelopes into bounded OpenClaw sessions and import only terminally confirmed, metadata-only result artifacts and evidence.", DispositionAdaptedForHAI, "partial", "delegated_session_terminal_stale_and_metadata_artifact_reconciliation_contract_tested", "documented", []string{multiAgent, protocol}), "P1", "Add an owner-bound agent-team message binding and acknowledgment mapping before delegation can report a team-message outcome.", "OpenClaw gateway client", "typed HAI task/result schema", "cancellation and timeout contract"),
		deferred(feature("openclaw-scheduling", "Background jobs, schedules, events, and triggers", "Run recurring or event-driven agent work.", "Gateway events and scheduled jobs can trigger agent turns without an active UI.", []string{"background_tasks", "scheduling", "events_and_triggers"}, []string{"Gateway", "scheduler", "configured channels"}, "MIT", "An upstream scheduler must not bypass HAI standing mandates, approval freshness, or the emergency stop.", "HAI durable scheduler, proactivity monitor, workflow leases, and reminder ledger", "Reuse upstream cron and event facilities through HAI-authorized job bindings; HAI owns mandates, budgets, approvals, deduplication, and emergency stop.", DispositionAdaptedForHAI, "partial", "hai_scheduler_tested", "documented", []string{readme, openClawRepo + "/blob/main/docs/automation/cron-jobs.md"}), "P1", "Map Gateway jobs and triggers to durable HAI operations, reconcile cancellation and duplicate delivery, and verify pause/restart behavior before enabling upstream schedules.", "job and trigger identity mapping", "mandate and budget checks", "duplicate-fire and emergency-stop acceptance"),
		deferred(feature("openclaw-host-tools", "Browser, computer, coding, shell, and file tools", "Allow an agent to interact with a device and development workspace.", "Main-session tools can run on the host; workspaces are a default working directory, not confinement.", []string{"browser_interaction", "computer_interaction", "coding_capabilities", "shell_and_script_execution", "file_operations"}, []string{"host process", "browser/node companions", "filesystem"}, "MIT", "Upstream documentation explicitly warns that host tools are not sandboxed by workspace boundaries.", "HAI execution broker, pathsafety, browser contracts, and approval proofs", "Reuse OpenClaw browser, computer, coding, shell, and file implementations through upstream tool policy and sandbox controls beneath HAI authorization; do not rebuild tool bodies or expose unrestricted host access.", DispositionDeferred, "not_implemented", "boundary_tested", "documented", []string{readme, multiAgent, openClawRepo + "/blob/main/docs/gateway/sandboxing.md"}), "P0", "Bind reviewed upstream tools to HAI capability authority, workspace/network scope, budgets, cancellation, and independent effect verification; these tools remain in scope pending sandbox acceptance.", "upstream sandbox and tool-policy contract", "exact capability authorization", "filesystem/network containment acceptance", "real tool cancellation and effect verification"),
		blocked(feature("openclaw-channels", "Messaging and communication channels", "Receive and deliver messages through WhatsApp, Telegram, Slack, Discord, Signal, and other channels.", "Channel adapters pair accounts and route conversations through the Gateway.", []string{"communication_integrations"}, []string{"provider accounts", "channel credentials", "pairing", "Gateway"}, "MIT", "Inbound messages are untrusted; outbound messages can create legal, social, or financial commitments.", "HAI connected sources, approval queue, communication drafting, and source provenance", "Use channels first as source intake. Outbound delivery requires a channel-specific approval/effect adapter and independent delivery verification.", DispositionBlockedExternal, "not_implemented", "not_tested", "source_reviewed", []string{readme, openClawRepo + "/tree/main/docs/channels"}), "P1", "Implement one read-only sandbox account before any send path; preserve message IDs and delivery receipts.", "owner credentials", "provider sandbox account", "channel-specific approval policy"),
		deferred(feature("openclaw-models", "Model providers, routing, local models, and cost controls", "Select hosted or local models for agent turns.", "OpenClaw configures model providers and runtime routes, including local and external model references.", []string{"model_providers", "model_routing", "local_models", "cost_management"}, []string{"provider credentials or local endpoint", "model configuration"}, "MIT", "A subordinate runtime must not spend money or silently select a paid model outside HAI's EUR 0 policy.", "HAI LLM router, provider quota ledger, telemetry, and model intelligence", "Reuse OpenClaw providers and model execution while HAI authorizes the exact model, fallback policy, and budget; retain source-backed session usage separately from per-run billing and quota debits.", DispositionAdaptedForHAI, "partial", "approved_start_model_and_typed_session_usage_contract_tested", "documented", []string{readme, openClawRepo + "/blob/main/docs/concepts/models.md", protocol}), "P0", "Start-model selection is approval-bound and native session usage has typed storage with durable recovery. Implement fallback authorization, cost ceiling enforcement, and per-call/provider billing reconciliation; reported model groups are not fallback chronology or per-run charges.", "fallback and cost ceiling enforcement", "real provider usage reconciliation", "owner-scoped usage and budget UI"),
		deferred(feature("openclaw-security", "Scopes, credentials, approvals, and sandbox controls", "Authenticate clients and limit which control-plane operations they may request.", "Gateway challenge/response, roles, scopes, pairing, tool policy, and optional sandboxing protect access.", []string{"permissions", "approval_systems", "sandboxing", "credential_handling"}, []string{"gateway credentials", "scope configuration", "sandbox runtime"}, "MIT", "Gateway scopes and client capabilities do not replace HAI effect authorization or current owner approval.", "HAI RBAC, Constitution, execution authorization, secret redaction, and emergency stop", "Enforce a Gateway method-to-scope allowlist and keep credentials in HAI's configured secret boundary; each external effect still needs HAI authorization.", DispositionAdaptedForHAI, "partial", "gateway_scope_handshake_method_allowlist_and_error_boundary_tested", "source_reviewed", []string{protocol, security, openClawRepo + "/blob/main/docs/gateway/sandboxing.md"}), "P0", "Add credential-store and sandbox acceptance tests before treating a configured Gateway as execution-ready.", "protocol schema pin", "credential storage design", "sandbox acceptance test"),
		deferred(feature("openclaw-resilience", "Recovery, retries, and checkpoints", "Resume sessions and avoid duplicate or stale transcript commits.", "Gateway transcript commits use fencing, session binding, compare-and-swap, and durable sequence replay.", []string{"recovery", "retry_behaviour", "checkpointing"}, []string{"Gateway", "session database", "trace IDs"}, "MIT", "Runtime retry must not duplicate an external effect or overwrite HAI's operation ledger.", "HAI leases, fencing tokens, idempotency, operation receipts, and review queue", "Persist an owner-bound receipt and stable idempotency key for every delegated runtime turn; reconcile ambiguous outcomes before any retry and route stale or indeterminate observations to review.", DispositionAdaptedForHAI, "partial", "delegated_session_idempotency_terminal_stale_and_metadata_artifact_reconciliation_contract_tested", "source_reviewed", []string{protocol}), "P0", "Validate the persisted receipt, idempotency, stale-review, and indeterminate-outcome boundary against a pinned local Companion before treating the runtime as execution-ready.", "stable OpenClaw request identity", "runtime receipt schema", "crash/replay fixtures", "pinned local Companion acceptance"),
		deferred(feature("openclaw-observability", "Events, logs, metrics, and tool lifecycle", "Expose runtime progress and diagnostics without treating traces as truth.", "Gateway events include tool lifecycle and trace context; runtime logs and status commands provide diagnostics.", []string{"observability", "logs", "metrics"}, []string{"Gateway event stream", "trace context"}, "MIT", "Tool events can contain secrets or large untrusted payloads and do not independently prove an effect.", "HAI audit log, operation ledger, runtime attempts, health and verification", "Redact and project bounded lifecycle events into HAI while retaining runtime IDs and source timestamps.", DispositionAdaptedForHAI, "partial", "health_probe_tested", "source_reviewed", []string{protocol, readme}), "P1", "Define redacted event schemas, retention limits, and evidence-vs-telemetry labels.", "event fixtures", "redaction review", "retention policy"),
		deferred(feature("openclaw-product-shell", "Control UI, configuration, installation, deployment, updates, tests, and documentation", "Operate OpenClaw as its own complete product.", "OpenClaw ships a Control UI, CLI/TUI, installers, release channels, configuration, CI, and documentation.", []string{"user_interfaces", "configuration", "installation", "deployment", "updates", "testing", "documentation"}, []string{"OpenClaw distribution", "Node.js", "operator-managed deployment"}, "MIT", "Importing a second dashboard and updater would create duplicate control planes and an uncontrolled supply-chain path.", "HAI dashboard, local Compose, CI, operator runbook, and update policy", "Reuse supported OpenClaw installation, configuration, update, and diagnostics facilities behind HAI controls; retain one HAI product interface and reviewed runtime versions.", DispositionAdaptedForHAI, "partial", "maintenance_http_worker_and_installer_contract_tested", "documented", []string{readme, openClawRepo + "/blob/main/docs/install/updating.md"}), "P0", "Complete live deployment and startup of the existing maintenance bridge, native prerequisite handling, upstream configuration controls, and upgrade/recovery acceptance; product differences do not exclude reusable infrastructure.", "installed maintenance worker and migration", "verified Node prerequisites", "owner-controlled configuration bridge", "live update and recovery acceptance"),
	}
}

func hermesFeatures() []RuntimeFeature {
	readme := hermesRepo + "/blob/main/README.md"
	apiServer := hermesRepo + "/blob/main/website/docs/user-guide/features/api-server.md"
	desktop := hermesRepo + "/blob/main/apps/desktop/README.md"
	skills := hermesRepo + "/blob/main/website/docs/user-guide/features/skills.md"
	memory := hermesRepo + "/blob/main/website/docs/user-guide/features/memory.md"
	windows := hermesRepo + "/blob/main/website/docs/user-guide/windows-native.md"
	return []RuntimeFeature{
		deferred(feature("hermes-protocol", "Headless gateway and OpenAI-compatible agent API", "Expose the Hermes agent loop through a stable local service surface.", "`hermes serve` provides a JSON-RPC/WebSocket gateway and the API server offers an OpenAI-compatible endpoint with streaming tool progress.", []string{"agent_runtimes", "agent_definitions", "goal_handling"}, []string{"Python 3.11+", "Hermes runtime", "configured model provider"}, "MIT", "An OpenAI-compatible endpoint can trigger terminal, file, web, memory, and skill tools; reachability is not permission.", "Runtime Lab adapter and HAI execution authorization", "Implement protocol-specific discovery and a bounded task envelope beneath HAI authority; never expose the generic endpoint directly to workflow execution.", DispositionAdaptedForHAI, "partial", "health_probe_only", "source_reviewed", []string{readme, apiServer, desktop}), "P0", "Implement version/capability handshake and non-executing discovery before a separately authorized task method.", "Pinned Hermes release", "loopback endpoint", "JSON-RPC fixtures", "operator-managed provider"),
		feature("hermes-planning", "Agent loop, planning, and reasoning skills", "Use a model and tools to decompose and complete requests.", "Hermes combines a general agent loop with prompt/skill-driven planning patterns.", []string{"planning", "replanning", "reasoning_patterns"}, []string{"model provider", "toolsets", "skills"}, "MIT", "Hermes must not replace HAI goals, plans, approvals, or completion decisions.", "HAI meta-controller, Plan Graph, task engine, workflow engine", "Retain HAI-native planning and delegate only bounded subtasks with explicit success and return schemas.", DispositionConsolidated, "implemented", "hai_planning_tested", "documented", []string{readme, skills}),
		deferred(feature("hermes-capabilities", "Tools, MCP, skills, and learned extensions", "Provide reusable capabilities and teach the agent new workflows from sources or experience.", "Hermes exposes toolsets, MCP integrations, slash-command skills, stacked skills, `/learn`, and optional self-evolution.", []string{"tool_use", "mcp", "skills", "plugins", "extensions"}, []string{"Hermes toolsets", "skill directories", "optional MCP servers"}, "MIT", "Generated skills and third-party tools are executable prompt and supply-chain inputs; self-improvement cannot change HAI authority.", "HAI capability cards, Brain Catalog, MCP preflight, controlled learning", "Import only reviewed skill metadata and bounded instruction artifacts; route learning through HAI's proposal, evidence, approval, and rollback lifecycle.", DispositionAdaptedForHAI, "partial", "hai_capability_and_learning_contracts_tested", "source_reviewed", []string{skills, hermesRepo + "/blob/main/website/docs/user-guide/features/mcp.md"}), "P0", "Add read-only skill/tool discovery with digest and provenance; reject autonomous code or policy mutation.", "Hermes discovery protocol", "skill schema", "supply-chain review", "controlled-learning adapter"),
		feature("hermes-memory", "Bounded profile memory and session context", "Remember stable preferences and lessons between sessions without unbounded prompt growth.", "Per-profile MEMORY.md and USER.md have strict character limits and are injected as a frozen session-start snapshot.", []string{"memory", "context_management", "knowledge_retrieval"}, []string{"Hermes home/profile", "memory files"}, "MIT", "Two writers sharing one Hermes home can corrupt authorship; automatic memory writes are model-generated claims until verified.", "HAI typed memory, provenance, confidence, review, and owner/project isolation", "Keep HAI memory canonical. If used, ingest reviewed Hermes memory changes as proposals with source and profile provenance.", DispositionConsolidated, "implemented", "hai_memory_tested", "documented", []string{memory}),
		deferred(feature("hermes-multi-agent", "Profiles, delegation, and parallel agent work", "Run isolated specialists and exchange bounded work products.", "Hermes profiles isolate homes and memory; its broader ecosystem can run managed or parallel agent sessions.", []string{"multi_agent_orchestration", "delegation", "parallel_execution"}, []string{"separate profiles", "gateway sessions", "typed HAI handoffs"}, "MIT", "Shared homes create conflicting memory; conversational handoffs alone do not provide durable acknowledgment or authority.", "HAI agent teams, typed messages, acknowledgments, and Plan Graph", "Allocate a separate Hermes profile per HAI agent card and bind all work/results to HAI team, message, operation, and evidence IDs.", DispositionAdaptedForHAI, "partial", "hai_team_contract_tested", "source_reviewed", []string{memory, desktop}), "P1", "Add profile-aware session creation, cancellation, artifact return, and acknowledgment reconciliation.", "Hermes gateway client", "profile lifecycle", "typed task/result schemas"),
		deferred(feature("hermes-scheduling", "Cron, background jobs, events, and triggers", "Run recurring agent tasks and deliver results through configured gateways.", "Cron and interval jobs can invoke Hermes in the background and messaging gateways can receive or deliver work.", []string{"background_tasks", "scheduling", "events_and_triggers"}, []string{"croniter", "Hermes process", "optional messaging gateway"}, "MIT", "Hermes cron must not bypass HAI's leases, standing mandates, budgets, approvals, or emergency stop.", "HAI durable scheduler, proactivity monitor, workflow leases, and reminder ledger", "Keep scheduling in HAI and call a bounded Hermes capability only from an authorized HAI operation.", DispositionAlreadyPresent, "implemented", "hai_scheduler_tested", "documented", []string{readme, hermesRepo + "/blob/main/website/docs/user-guide/features/cron.md"}), "P2", "Only add a Hermes scheduler importer if migration of an existing schedule is needed.", "schedule import schema", "explicit owner migration"),
		excluded(feature("hermes-host-tools", "Browser, computer, coding, terminal, and file tools", "Research, edit code and files, and invoke local commands.", "Hermes exposes terminal, file, browser/web, and coding toolsets to its agent loop.", []string{"browser_interaction", "computer_interaction", "coding_capabilities", "shell_and_script_execution", "file_operations"}, []string{"host process", "browser/search providers", "filesystem"}, "MIT", "Generic terminal and file tools can escape project scope, leak secrets, or act on prompt injection.", "HAI execution broker, pathsafety, browser contracts, and approval proofs", "Do not pass through generic tools. Re-declare each needed operation as a HAI capability with exact roots, input/output schemas, authority, evidence, and verification.", DispositionConstrainedUnsafe, "excluded", "boundary_tested", "documented", []string{readme, apiServer}), "Unbounded host tools conflict with HAI's read-only default and effect-specific authorization."),
		blocked(feature("hermes-channels", "Messaging gateways, email, and voice", "Receive tasks and deliver agent responses through communication surfaces.", "Hermes supports messaging gateways and optional voice/TTS integrations.", []string{"communication_integrations"}, []string{"channel accounts", "gateway credentials", "optional TTS/provider services"}, "MIT", "Inbound content is untrusted; outbound delivery can make commitments and may expose sensitive context.", "HAI source connectors, drafting, approval queue, and local reminders", "Use communication surfaces as intake first; authorize any send with a channel-specific immutable effect receipt and delivery verification.", DispositionBlockedExternal, "not_implemented", "not_tested", "source_reviewed", []string{readme, hermesRepo + "/tree/main/website/docs/integrations"}), "P1", "Implement one read-only sandbox channel and retain provider IDs before considering send.", "owner credentials", "sandbox account", "channel approval and verification adapter"),
		feature("hermes-models", "Model providers, local models, routing, and cost", "Run Hermes across configured hosted or local models.", "Hermes supports provider selection and an optional Nous gateway spanning many models and tool services.", []string{"model_providers", "model_routing", "local_models", "cost_management"}, []string{"provider or local model endpoint", "Hermes provider configuration"}, "MIT", "Nous Portal and other providers can incur cost; an external runtime must not override HAI's paid-disabled policy.", "HAI LLM router, EUR 0 policy, quotas, telemetry, and model intelligence", "Select and budget the model in HAI and pass an exact approved provider/model constraint to Hermes where enforceable.", DispositionConsolidated, "implemented", "hai_router_tested", "documented", []string{readme, hermesRepo + "/blob/main/website/docs/integrations/providers.md"}),
		deferred(feature("hermes-security", "Permissions, approvals, sandboxing, and credentials", "Control which runtime capabilities and providers are available.", "Profiles, toolsets, provider credentials, and gateway configuration bound Hermes behavior, but its general tools remain powerful.", []string{"permissions", "approval_systems", "sandboxing", "credential_handling"}, []string{"Hermes profile", "credential store", "toolset configuration"}, "MIT", "Hermes configuration is not HAI approval; generic tools need process and filesystem confinement.", "HAI RBAC, Constitution, execution authorization, secrets, and emergency stop", "Map every Hermes method/tool to a minimum HAI capability and require a sandbox plus current effect authorization for execution.", DispositionAdaptedForHAI, "partial", "url_and_redirect_boundary_tested", "source_reviewed", []string{readme, hermesRepo + "/blob/main/SECURITY.md"}), "P0", "Define protocol method allowlist, credential boundary, and sandbox acceptance suite.", "Hermes protocol schema", "process sandbox", "method-to-permission matrix"),
		deferred(feature("hermes-resilience", "Recovery, retries, checkpoints, and profile continuity", "Continue long-running or interrupted agent work without duplicating effects.", "Gateway sessions, profiles, cron state, and persisted memory provide continuity across processes.", []string{"recovery", "retry_behaviour", "checkpointing"}, []string{"gateway session identity", "profile state", "HAI operation ID"}, "MIT", "Retrying a conversational turn can duplicate tools; memory does not prove an external effect.", "HAI operation ledger, leases, idempotency, review queue, and verification", "Fence every Hermes call with one HAI operation and reconcile tool receipts before retry or resume.", DispositionAdaptedForHAI, "partial", "hai_recovery_contract_tested", "source_reviewed", []string{desktop, memory}), "P0", "Add idempotency, cancellation, bounded checkpoint, and ambiguous-outcome fixtures to the future adapter.", "stable runtime request ID", "tool receipt schema", "crash/replay tests"),
		deferred(feature("hermes-observability", "Streaming progress, logs, metrics, and tool summaries", "Show what the runtime is doing and diagnose failures.", "Gateway/API streaming exposes tool progress and structured summaries while local logs record runtime activity.", []string{"observability", "logs", "metrics"}, []string{"gateway event stream", "runtime logs"}, "MIT", "Progress streams can leak tool payloads and are not independent verification.", "HAI audit, runtime attempts, operation ledger, and verification evidence", "Redact and store bounded lifecycle events as telemetry, never as effect proof.", DispositionAdaptedForHAI, "partial", "health_probe_tested", "source_reviewed", []string{apiServer, desktop}), "P1", "Define event redaction, retention, and trace correlation before streaming into HAI.", "event fixtures", "redaction policy", "trace mapping"),
		excluded(feature("hermes-product-shell", "Desktop/dashboard, configuration, installation, deployment, updates, tests, and docs", "Operate Hermes as an independent agent product across desktop and browser surfaces.", "Hermes ships CLI, dashboard, Electron desktop, managed installation/update behavior, platform guides, tests, and documentation.", []string{"user_interfaces", "configuration", "installation", "deployment", "updates", "testing", "documentation"}, []string{"Hermes distribution", "Python", "optional Electron desktop"}, "MIT", "A second dashboard/updater would duplicate HAI and could mutate the runtime outside HAI's reviewed update policy.", "HAI dashboard, Compose, CI, operator runbook, and update governance", "Keep Hermes separately installed and pinned. HAI shows capability, readiness, attempts, evidence, and setup requirements only.", DispositionExcludedIrrelevant, "excluded", "not_applicable", "documented", []string{desktop, windows, readme}), "Hermes product surfaces duplicate HAI; the protocol and selected capabilities are the integration targets."),
	}
}

func odysseusFeatures() []RuntimeFeature {
	readme := odysseusRepo + "/blob/dev/README.md"
	security := odysseusRepo + "/blob/dev/SECURITY.md"
	threat := odysseusRepo + "/blob/dev/THREAT_MODEL.md"
	roadmap := odysseusRepo + "/blob/dev/ROADMAP.md"
	return []RuntimeFeature{
		deferred(feature("odysseus-runtime", "Self-hosted workspace and agent sessions", "Provide one workspace for chat, agents, research, documents, and local workflows.", "A Python web application hosts user sessions, agent mode, privileged tools, and internal services.", []string{"agent_runtimes", "agent_definitions", "goal_handling"}, []string{"Odysseus service", "Python", "database and optional sidecars"}, "AGPL-3.0-or-later", "Its threat model treats a logged-in admin as fully privileged, including shell and file access.", "Runtime Lab adapter and HAI agent-team contracts", "Interoperate only with a separately deployed Odysseus API after legal/security review; do not copy or link its server code into HAI.", DispositionDeferred, "not_implemented", "health_probe_only", "source_reviewed", []string{readme, threat}), "P2", "Define a narrow remote protocol for read-only capability discovery before any agent task.", "separate AGPL deployment", "legal review", "pinned API contract", "private-network endpoint"),
		feature("odysseus-planning", "Agent reasoning and research workflows", "Plan tool use and conduct multi-step source-backed research.", "Agent and Deep Research modes combine prompts, tools, web retrieval, and report generation.", []string{"planning", "replanning", "reasoning_patterns"}, []string{"model provider", "search/fetch services", "agent tools"}, "AGPL-3.0-or-later", "A generated research report is not verified truth and upstream planning must not own HAI completion.", "HAI task classifier, Plan Graph, grounded answers, and verification", "Retain HAI-native planning and source-grounding; use Odysseus only as an optional bounded research capability after protocol review.", DispositionHAINative, "implemented", "hai_planning_and_grounding_tested", "documented", []string{readme, roadmap}),
		excluded(feature("odysseus-capabilities", "Tools, MCP, skills, plugins, and extensions", "Extend agents with files, shell, application APIs, skills, and MCP tools.", "Admin sessions can invoke broad tools; non-admin users are restricted from MCP and privileged operations.", []string{"tool_use", "mcp", "skills", "plugins", "extensions"}, []string{"Odysseus tool loop", "optional MCP servers", "admin session"}, "AGPL-3.0-or-later", "The internal-tool loopback has admin authority and broad tools are intentionally privileged.", "HAI capability cards, MCP preflight, allowlists, and execution authorization", "Do not import implementation code. Reproduce only needed behavior through HAI-native schemas or a separately deployed read-only capability adapter.", DispositionExcludedIncompatibleLicense, "excluded", "hai_boundary_tested", "documented", []string{readme, threat, security}), "Direct source integration would combine AGPL server implementation with HAI; remote interoperability remains a separately reviewed option."),
		feature("odysseus-memory", "Memory, documents, notes, and knowledge retrieval", "Store and retrieve workspace knowledge for chat, research, and tasks.", "Odysseus combines saved memory, uploads, documents, notes, search, and optional vector services.", []string{"memory", "context_management", "knowledge_retrieval"}, []string{"Odysseus data store", "optional ChromaDB", "uploads"}, "AGPL-3.0-or-later", "Saved memories and documents are untrusted input; raw private data must not cross runtimes without explicit scope.", "HAI source registry, extraction, evidence, memory, and retrieval limits", "Keep HAI canonical. Import only source-linked exports through a connector; never mount the same storage or share credentials.", DispositionConsolidated, "implemented", "hai_memory_and_source_tested", "documented", []string{readme, threat}),
		feature("odysseus-multi-agent", "Agent assignment, delegation, and parallel work", "Assign workspace tasks to specialist agents and combine outputs.", "The workspace supports agent sessions and its roadmap includes stronger task-to-agent assignment; complete durable multi-agent authority is not documented.", []string{"multi_agent_orchestration", "delegation", "parallel_execution"}, []string{"agent sessions", "tasks", "model providers"}, "AGPL-3.0-or-later", "Conversational agent sessions do not provide HAI's immutable delegation, acknowledgment, approval, or completion evidence.", "HAI agent teams, Plan Graph, messages, acknowledgments, and operation ledger", "Use HAI-native orchestration; optionally delegate a bounded research subtask to a separate Odysseus runtime later.", DispositionHAINative, "partial", "hai_team_contract_tested", "source_reviewed", []string{readme, roadmap}),
		feature("odysseus-scheduling", "Tasks, reminders, Calendar, background jobs, and triggers", "Track work and run scheduled agent tasks with calendar synchronization.", "Odysseus provides reminders, todos, scheduled tasks, and CalDAV-oriented calendar behavior.", []string{"background_tasks", "scheduling", "events_and_triggers"}, []string{"scheduler", "optional CalDAV", "Odysseus service"}, "AGPL-3.0-or-later", "Calendar writes and scheduled agents can create commitments without current HAI approval.", "HAI workflow scheduler, reminder ledger, Calendar read connector, and approval queue", "Retain HAI scheduling and adapt useful interaction behavior only; external Calendar write remains separately authorized and unimplemented.", DispositionAlreadyPresent, "implemented", "hai_scheduler_tested", "documented", []string{readme, roadmap}),
		excluded(feature("odysseus-host-tools", "Browser, computer, coding, shell, and file tools", "Let an admin agent operate the local machine and workspace.", "Shell and file tools run as the application process user without filesystem confinement or network egress filtering.", []string{"browser_interaction", "computer_interaction", "coding_capabilities", "shell_and_script_execution", "file_operations"}, []string{"admin session", "host process", "filesystem", "network"}, "AGPL-3.0-or-later", "The upstream threat model explicitly lists no shell/filesystem sandbox and warns of prompt-injection-driven outbound access.", "HAI execution broker, pathsafety, browser contracts, and approval proofs", "Never expose these tools through the generic Odysseus admin loop. Re-declare bounded operations as HAI-native capabilities with sandbox and evidence.", DispositionConstrainedUnsafe, "excluded", "hai_boundary_tested", "documented", []string{threat, security}), "Unconfined admin tools conflict with HAI's owner-scoped, effect-specific execution boundary."),
		blocked(feature("odysseus-communications", "Email, Calendar, notes, and communication workflows", "Triage email, draft replies, track reminders, and synchronize calendar data.", "Odysseus supports IMAP/SMTP email and CalDAV-oriented workspace functions; admin privileges gate sensitive operations.", []string{"communication_integrations"}, []string{"email/Calendar credentials", "private-network deployment", "provider services"}, "AGPL-3.0-or-later", "SMTP and calendar mutation are external effects; fetched content is prompt-injection input.", "HAI Gmail/Calendar source connectors, drafting, approval queue, and source evidence", "Retain HAI read-only connectors and approval-first drafting. A separate Odysseus deployment may be a source only after provenance and least-privilege testing.", DispositionBlockedExternal, "not_implemented", "not_tested", "source_reviewed", []string{readme, threat, security}), "P2", "Do not add write paths; first prove read-only sandbox ingestion with source IDs and revocation.", "sandbox accounts", "least-privilege credentials", "provider acceptance evidence"),
		feature("odysseus-models", "Provider setup, local models, Cookbook, Compare, routing, and cost", "Run and compare hosted or local models and recommend hardware-appropriate configurations.", "Provider probes, local model serving, a hardware-aware Cookbook, and blind model comparison support model selection.", []string{"model_providers", "model_routing", "local_models", "cost_management"}, []string{"Ollama/vLLM/llama.cpp or provider APIs", "hardware profile"}, "AGPL-3.0-or-later", "Model serving exposes powerful internal ports; provider selection can incur cost and comparison is not production validation.", "HAI model intelligence, hardware profile, LLM router, telemetry, and EUR 0 policy", "Adapt the hardware-fit and blind-comparison concepts through HAI-native model evidence; do not import AGPL implementation.", DispositionHAINative, "partial", "hai_model_contracts_tested", "documented", []string{readme, roadmap}),
		excluded(feature("odysseus-security", "Authentication, permissions, approvals, sandboxing, and credentials", "Protect a privileged self-hosted workspace and restrict non-admin tools.", "Sessions, 2FA, privilege defaults, reserved usernames, middleware, and an internal admin loopback protect access; admins remain unrestricted.", []string{"permissions", "approval_systems", "sandboxing", "credential_handling"}, []string{"Odysseus auth store", "reverse proxy/private network", "admin account"}, "AGPL-3.0-or-later", "Admin always has full access, internal-tool receives admin authority, shell/filesystem is not sandboxed, and the threat model documents an SSRF risk.", "HAI IDP/RBAC, execution authorization, Constitution, secrets, and emergency stop", "Do not reuse Odysseus auth or internal admin loopback. Keep HAI identity and approval authoritative and require a narrow service credential for remote discovery.", DispositionConstrainedUnsafe, "excluded", "hai_security_contracts_tested", "documented", []string{threat, security}), "Odysseus's trusted-admin boundary is materially broader than HAI's per-effect authority model."),
		deferred(feature("odysseus-resilience", "Recovery, retries, checkpoints, and scheduled-task continuity", "Recover workspace and background work after interruption.", "Persistent workspace data and scheduled task state provide continuity, while roadmap items identify degraded-state visibility gaps.", []string{"recovery", "retry_behaviour", "checkpointing"}, []string{"Odysseus database", "scheduler", "service health"}, "AGPL-3.0-or-later", "Retrying an admin tool can duplicate email, file, or calendar effects; upstream state is not HAI canonical state.", "HAI operation ledger, leases, idempotency, review queue, and verification", "If a remote adapter is built, bind every request to a HAI operation and reconcile ambiguous outcomes before retry.", DispositionDeferred, "not_implemented", "not_tested", "source_reviewed", []string{roadmap, threat}), "P2", "Define a read-only runtime receipt/status protocol before any resumable task.", "separate service", "stable request ID", "receipt schema", "crash/replay tests"),
		deferred(feature("odysseus-observability", "Health, logs, metrics, and degraded-state reporting", "Show availability and failure of workspace sidecars and providers.", "The workspace has health/probe behavior, while its roadmap calls out clearer degraded states for search, vector, email, notification, and provider services.", []string{"observability", "logs", "metrics"}, []string{"Odysseus health endpoints", "optional sidecars"}, "AGPL-3.0-or-later", "A single health endpoint can hide sidecar failure and logs may contain credentials or personal data.", "HAI Runtime Lab, readiness matrix, redaction, attempts, and audit", "Probe only documented allowlisted endpoints and record each dependency separately; never ingest raw logs by default.", DispositionAdaptedForHAI, "partial", "generic_health_probe_tested", "source_reviewed", []string{roadmap, security}), "P2", "Add versioned dependency-health schema if the upstream service publishes one.", "documented health contract", "redaction review", "sidecar fixtures"),
		excluded(feature("odysseus-product-shell", "Workspace UI, configuration, installation, deployment, updates, tests, and documentation", "Operate Odysseus as a complete independent self-hosted product.", "Odysseus ships a web UI, Docker deployment, Windows helpers, configuration, updates, tests, and extensive product features.", []string{"user_interfaces", "configuration", "installation", "deployment", "updates", "testing", "documentation"}, []string{"separate Odysseus deployment", "Docker or native Python"}, "AGPL-3.0-or-later", "Merging the product shell would create a second control plane and trigger AGPL obligations for a combined network service.", "HAI dashboard, Compose, CI, operator runbook, and update governance", "Keep any Odysseus deployment separate and operator-managed; HAI may show only reviewed readiness and capability metadata.", DispositionExcludedIncompatibleLicense, "excluded", "not_applicable", "documented", []string{readme, security, odysseusRepo + "/blob/dev/LICENSE"}), "The AGPL product shell is not imported into the canonical HAI codebase; HAI already owns these product concerns."),
	}
}
