#!/usr/bin/env bash
#
# Generate real secrets for a local HAI stack.
#
# The values shipped in .env.example ("change-this-...") are placeholders. With
# RUN_MODE=production the backend reports /readyz as not_ready while any of them
# is still in place, so this script exists to make doing the right thing a
# one-liner:
#
#   ./scripts/generate-secrets.sh >> .env.local
#
# Then remove the older duplicate keys, or regenerate .env.local from scratch:
#
#   cp .env.example .env.local
#   ./scripts/generate-secrets.sh >> .env.local
#
# The owner email is prompted for when FIRST_RUN_ADMIN_EMAIL is unset. Set that
# variable explicitly for non-interactive use. Appending this output overrides
# both the template email and the secret placeholders above it.

set -euo pipefail

if ! command -v openssl >/dev/null 2>&1; then
  echo "openssl is required to generate secrets" >&2
  exit 1
fi

if [[ -z "${FIRST_RUN_ADMIN_EMAIL:-}" ]]; then
  if ! { exec 3<>/dev/tty; } 2>/dev/null; then
    echo "Set FIRST_RUN_ADMIN_EMAIL or run this script interactively to choose the first-run owner email." >&2
    exit 1
  fi
  printf 'First-run owner email: ' >&3
  if ! IFS= read -r FIRST_RUN_ADMIN_EMAIL <&3; then
    exec 3>&-
    echo "Could not read the first-run owner email. Set FIRST_RUN_ADMIN_EMAIL or run this script interactively." >&2
    exit 1
  fi
  exec 3>&-
fi

FIRST_RUN_ADMIN_EMAIL="$(printf '%s' "$FIRST_RUN_ADMIN_EMAIL" | sed 's/^[[:space:]]*//; s/[[:space:]]*$//' | tr '[:upper:]' '[:lower:]')"
if [[ ! "$FIRST_RUN_ADMIN_EMAIL" =~ ^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$ ]]; then
  echo "FIRST_RUN_ADMIN_EMAIL must be a valid email address using letters, numbers, and ._%+- in the local part." >&2
  exit 1
fi

secret() { openssl rand -hex 32; }

# Generate everything before writing stdout so a failed entropy request cannot
# leave a partially generated env-file fragment.
backend_api_shared_key="$(secret)"
local_preview_gateway_secret="$(secret)"
memory_encryption_key="$(secret)"
jwt_secret="$(secret)"
approval_proof_signing_key="$(secret)"
db_password="$(secret)"
first_run_admin_password="$(secret)"

cat <<EOF

# --- Generated secrets ($(date -u +%Y-%m-%dT%H:%M:%SZ)) ---
# Generated by scripts/generate-secrets.sh. Do not commit this file.
FIRST_RUN_ADMIN_EMAIL=$FIRST_RUN_ADMIN_EMAIL
BACKEND_API_SHARED_KEY=$backend_api_shared_key
LOCAL_PREVIEW_GATEWAY_SECRET=$local_preview_gateway_secret
HAI_MEMORY_ENCRYPTION_KEY=$memory_encryption_key
JWT_SECRET=$jwt_secret
HAI_APPROVAL_PROOF_SIGNING_KEY=$approval_proof_signing_key
DB_PASSWORD=$db_password
FIRST_RUN_ADMIN_PASSWORD=$first_run_admin_password
EOF
